language: ruby

script:
  - bundle exec rake test

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.0
  - 2.3.1

env:
#  - DB=sqlite # there is a regression in Rails 4.2 where sqlite doesn't work. Uncomment this in next release after 4.2.1
  - DB=mysql
  - DB=mysql2
  - DB=postgresql

before_script:
  - mysql -e 'create database filterrific_demo_test;'
  - psql -c 'create database filterrific_demo_test;' -U postgres

branches:
  except:
    - master
